### ISSUE TITLE
Abstração de tipos de usuários.

### ISSUE THREAD

**Issue by MisaelAugusto** [samuelcomputacao/ProjetoDevWeb#13]
Dentro do contexto de usuários, tu pode criar uma interface User, que define os dados de um usuário. Depois definir duas outras interfaces, cliente e funcionário, ambas extendendo a interface User. Assim, tu não precisa de vários estados pra armazenar os dados do usuário ou de métodos duplicados pra verificar o tipo de usuário.

**Comment by samuelcomputacao** [comment]
Não estou trabalhando com classes e sim componentes funcionais.
