### ISSUE TITLE
Excesso de rotas?

### ISSUE THREAD

**Issue by matheusgr** [samuelcomputacao/ProjetoDevWeb#3]
https://github.com/samuelcomputacao/ProjetoDevWeb/blob/4fedb1e28426dbe9390d945ff4601218e8aa0a47/frontend/src/routes.js#L20-L24

As rotas no cliente trabalham com funcionalidades. Tipicamente não faz muito sentido ter uma tela a parte para editar e outra para cadastrar os recursos. Tu já planejou como serão essas telas?

Também não sei se é legal, pro escopo do projeto, focar na adição/cadastro dos usuários. O cadastro de hortaliças e de pedidos já deve ser bem custoso.

**Comment by samuelcomputacao** [comment]
Vou reavaliar essas rotas
